version: '3.2'

services:

  scaife-viewer:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: scaife-viewer
    volumes:
      - .:/usr/src/app/
    entrypoint: /usr/src/app/entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8001:8000
    environment:
      - SECRET_KEY=-!%+c%7ur9r#hpj3(9c_-u8nj7#*7+v+t(%-ks9(qj3mbq6f)=
      - DEBUG=1
      - DATABASE_URL=postgres://scaife:scaife@postgres:5432/postgres
      - ELASTICSEARCH_HOSTS=elasticsearch
      - CTS_RESOLVER=local
      - CTS_LOCAL_DATA_PATH=data
    depends_on:
      - postgres
      - elasticsearch

  postgres:
    image: postgres:10.5-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=scaife
      - POSTGRES_PASSWORD=scaife

  elasticsearch:
    build:
      context: ./
      dockerfile: Dockerfile-elastic
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  scaife-webpack:
    build:
      context: ./
      dockerfile: Dockerfile-webpack
    container_name: scaife-webpack
    volumes:
      - .:/usr/src/app/
    ports:
      - 8080:8080
